### ISSUE TITLE
As a developer i want to be able to send message CloudEvents for generic communication 

### ISSUE THREAD

**Issue by ilan-pinto** [open-accelerators/mercury#10]
## Feature Request
As a developer, I want to be able to send message CloudEvents for generic communication 
### Description of Problem:
BIAN defines only REST endpoints, however, most communication in FSI will happen asynchronously using different protocols  
BIAN defines 6 EventDriven Communications types
### Potential Solutions:
- using [CloudEvents](https://cloudevents.io/) as a commonly agreed specification for describing event data in a common way 
- try to define a solution for easily implementing the  EventDriven Communications types

### Important note 
this issue requires BIAN community adoption if we want to enhance the solution in the future.

**Comment by ilan-pinto** [comment]
@ruromero issue is closed but we actually only provided a proposal, right?

**Comment by ruromero** [comment]
It is now. It is being used in the current implementation
