### ISSUE TITLE
As a DevOps I want to know how to deploy my services (or routes) on OpenShift

### ISSUE THREAD

**Issue by ilan-pinto** [open-accelerators/mercury#11]
## Feature Request
As a DevOps I want to know how to deploy my services (or routes) on OpenShift **including any other Mercury components **

### Description of Problem:
FSI needs the flexibility to determine the  Mercury components to be deployed that can include: routs, microservices, security components, databases, and more 

### Potential Solutions:
- configurable pipeline 
- Mercury Framework operator

**Comment by ruromero** [comment]
The operator takes care of this part. Use the Custom Resources defined for the service domains to do so.
