### ISSUE TITLE
As a developer I expect that any service domain is available at any time and that it responds to a call.

### ISSUE THREAD

**Issue by ilan-pinto** [open-accelerators/mercury#13]
## Feature Request
As a developer, I expect that any service domain is available at any time and that it responds to a call.

### Description of Problem:
Mercury framework uses knative/camel-k serverless approach, which means that if there no calls the service will be down. 
that can cause delays in the response time 

### Potential Solutions:
- is it possible to have a service up all time? at least for most frequent used 

note: this problem exists only when interacting with REST API

**Comment by ruromero** [comment]
The operator is creating a deployment. It is not necessary at the moment to involve other technologies like KNative
